[build]
builder = "nixpacks"
buildCommand = "npm run build"

[variables]
NIXPACKS_NODE_VERSION = "20"

[deploy]
startCommand = "npx drizzle-kit migrate && npm run start"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
